--- 
clone: 
  depth: 1
kind: pipeline
name: FiqriPipeline
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/STRIX-Project/kernel_build_script/droneci/droneci-test-xiaomi.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: compile
    trigger: 
      branch: 
        - eas-sdm660-test
